### ISSUE TITLE
Add unit tests for running the test within the mobile browser.

### ISSUE THREAD

**Issue by mfaisalkhatri** [WasiqB/coteafs-appium#168]
As per the query raised in #167 @WasiqB  we need to add tests for mobile browsers as well for both iOS as well as android. 
Also, a sample config file with mobile browser setting needs to be updated in the documentation as well.

**Comment by mfaisalkhatri** [comment]
Following stack trace is generated while trying to run the tests on browser 
```
java.lang.NullPointerException: Cannot invoke "com.github.wasiqb.coteafs.appium.config.device.android.WebOptions.getArgs()" because "options" is null

	at com.github.wasiqb.coteafs.appium.device.Device.setChromeOptions(Device.java:393)
	at com.github.wasiqb.coteafs.appium.device.Device.setAndroidWebSetting(Device.java:380)
	at com.github.wasiqb.coteafs.appium.device.Device.setAndroidCapabilities(Device.java:370)
	at com.github.wasiqb.coteafs.appium.device.Device.setDeviceSpecificCapabilities(Device.java:430)
	at com.github.wasiqb.coteafs.appium.device.Device.setLocalCapabilities(Device.java:492)
	at com.github.wasiqb.coteafs.appium.device.Device.buildCapabilities(Device.java:288)
	at com.github.wasiqb.coteafs.appium.device.Device.<init>(Device.java:153)
	at com.github.wasiqb.coteafs.appium.android.AndroidDevice.<init>(AndroidDevice.java:40)
	at tests.DefaultTest.setupTest(DefaultTest.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
	at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
	at org.testng.TestRunner.beforeRun(TestRunner.java:627)
	at org.testng.TestRunner.run(TestRunner.java:589)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
```
